### ISSUE TITLE
Various options disappear from the Displays settings page when laptop main screen is disabled

### ISSUE THREAD

**Issue by J4ckWh0** [pop-os/cosmic-settings#777] opened 2024-11-19 15:38 UTC
![screenshot-2024-11-19-15-35-15](https://github.com/user-attachments/assets/8b32f3a9-9de1-4315-a2be-0a9e536638db)

With an intel laptop plugged into an external display all the various scaling, resolution and refresh rate settings disappear from the settings page. This happens when the main laptop display is disabled leaving the external display as the only active display.

If the main laptop display is re-enabled all the settings for the external display are accessible again.

**Comment by marchaesen** [comment] 2024-11-20 12:48
This is a duplicate of issue 767: https://github.com/pop-os/cosmic-settings/issues/767

**Closed** 2024-11-20 15:47 UTC
