### ISSUE TITLE
Bugs and glitches with keyboard shortcut settings

### ISSUE THREAD

**Issue by pbignardi** [pop-os/cosmic-settings#512] opened 2024-08-20 20:22 UTC
There is a bug (I imagine) in the Keyboard Shortcut sections of the settings.

Version: 0.1.0
Distribution: Arch (package distributed by arch repositories)

1) The entries for the workspace switching keybinds aren't in any of the **Keyboard Shortcuts** submenus (Manage Windows, Move Windows, etc...).
This is for sure a bug since searching for "switch" in the search bar shows that the entries are there, but for some reason are not listed in any of the submenus.

2) While changing these shortcuts, the panel on the right closes and all the entries on screen disappear (as in pictures). Despite these glitches, closing and reopening the settings app reveals that the changes are actually saved (though the entries are still missing).

![screenshot-2024-08-20-19-51-25](https://github.com/user-attachments/assets/74732edb-ba87-4038-8baf-414c17a3e590)
![screenshot-2024-08-20-20-17-11](https://github.com/user-attachments/assets/8bb3f076-6092-429b-86a2-bc5834e57ad2)
![screenshot-2024-08-20-20-17-17](https://github.com/user-attachments/assets/537288ac-06eb-4591-9641-aacfc0c0f471)

**Comment by WatchMkr** [comment] 2024-09-03 22:57
1. Thanks for catching this
2. I think this is a duplicate of https://github.com/pop-os/cosmic-settings/issues/525

**Closed** 2024-09-09 11:28 UTC
