### ISSUE TITLE
Some background color selections lead to no or almost no color tint on elements

### ISSUE THREAD

**Issue by benfuddled** [pop-os/cosmic-settings#504] opened 2024-08-18 01:14 UTC
This could be a matter of personal preference, so if this is the way the design system is intended to work feel free to close.

When the "Application or window background" setting is set to certain lighter colors, the main panel turns white. I feel like it would be better if they had a tiny bit more of the background color tint in these cases. Some examples:

### #D0DFEC

![D0DFEC](https://github.com/user-attachments/assets/e3fb8c4d-cd99-4238-a654-636ec1b5e023)

### #CBE7CE

![CBE7CE](https://github.com/user-attachments/assets/58179538-1e4a-499d-a7e7-04e4831990ef)

### #E4DCCD

![E4DCCD](https://github.com/user-attachments/assets/2ffe1001-55fe-4237-b12f-20e16807b839)

For this last example, here's a mockup of what it would look like with stronger tinting.

![E4DCCD-tinted](https://github.com/user-attachments/assets/2c5511b7-c3c1-4ef1-b541-166e5fc2d830)

And finally, here's an example of where the color tint really does shine through, hex code #D5BCE0:

![D5BCE0-visible](https://github.com/user-attachments/assets/fea63910-47f1-4854-b6ae-d776f5bea58e)

**Comment by maria-komarova** [comment] 2024-08-28 16:31
This is working as intended. We currently use steps in lightness to calculate the automatically derived colors. We still need to pass a certain level of contrast in order for the interface to function. Tinting might interfere with the contrast between various elements of the UI and also add even more complexity to a pretty complex system. In any case, it is probably out of scope for us for the first release.

**Closed** 2024-12-04 01:39 UTC
