### ISSUE TITLE
[Feature Request] Night Light 

### ISSUE THREAD

**Issue by Xpolo29** [pop-os/cosmic-settings#505] opened 2024-08-18 13:31 UTC
Hi I've seen [issue 310](https://github.com/pop-os/cosmic-settings/pull/310) saying that Night Light wasn't ready for alpha 1 so I'm just putting this here so it goes to alpha 2 roadmap.

Feature is a blue light filter like Night light in GNOME, where you can change start and end time based on schedule or location.

Also there should be the possibility to change light filter intensity.

Thanks !

**Comment by Department-stack** [comment] 2024-08-18 14:37
If this does get added then I think brightness should become its own applet and nightlight should be included in it

**Comment by git-f0x** [comment] 2024-08-18 22:19
It will be a post-release update, as mentioned on the 24.04 ISO webpage (COSMIC V1 is the full release of the first version of COSMIC). Whether that's Epoch 2 or a 1.1 update, I'm not sure.

**Comment by leviport** [comment] 2024-08-19 13:31
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/476

**Comment by Xpolo29** [comment] 2024-08-19 14:32
Welp didn't see this issue sorry, closing as duplicate

**Closed** 2024-08-19 14:32 UTC
