### ISSUE TITLE
 [Feature Request] Settings -> Desktop -> Appearance - Ability to change default font

### ISSUE THREAD

**Issue by cemkavuklu** [pop-os/cosmic-settings#527] opened 2024-08-27 21:26 UTC
Please add the ability to change the default font for the whole desktop.

And keep up the amazing work :)

**Comment by leviport** [comment] 2024-08-27 21:30
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/549

**Closed** 2024-09-12 00:57 UTC
