### ISSUE TITLE
Arabic settings and English options overlap.

### ISSUE THREAD

**Issue by ssoufi-code** [pop-os/cosmic-settings#816] opened 2024-12-12 10:18 UTC
When picking Arabic(Algeria), a right to left language, overlaps with the English language settings. This could be because Arabic reflects the language from left to right.
![Screenshot from 2024-12-12 02-16-17](https://github.com/user-attachments/assets/42f63210-2d05-4d6a-ae3c-ac738488ea52)

**Comment by leviport** [comment] 2024-12-12 15:22
Duplicate of https://github.com/pop-os/cosmic-settings/issues/537

**Closed by leviport** 2024-12-12 15:22 UTC
