### ISSUE TITLE
Cannot bind modifier + Space

### ISSUE THREAD

**Issue by curiousercreative** [pop-os/cosmic-settings#393] opened 2024-07-02 15:01 UTC
Prior to recent feature for keyboard shortcut binding in settings GUI, modifier + Space was a valid keybinding in /etc/cosmic-comp.config.ron. Now, the settings GUI will not validate or accept any modifier + Space keybinding. 

See chat [message](https://chat.pop-os.org/pop-os/pl/8shpdo868jnzzb75aof454dyrc) and [thread](https://chat.pop-os.org/pop-os/channels/cosmic-epoch/go7tgcr3jtrufezjf8d1tw13dy) for more discussion.

**Comment by mmstick** [comment] 2024-07-02 15:03
Duplicate of #390 which is already fixed

**Comment by mmstick** [comment] 2024-07-02 15:04
Nevermind. I do see that the name is case-sensitive

**Closed** 2024-07-02 15:06 UTC

**Comment by Beethoven-n** [comment] 2024-10-06 00:07
i tried doing Super+Space as a hotkey and it didn't work, am i doing it wrong?
