### ISSUE TITLE
[Settings Request] Enabled tap-to-click for mouse input by default

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/cosmic-settings#254] opened 2024-04-30 15:12 UTC
This is default in most distros including current Pop COSMIC+GNOME.

**Comment by WatchMkr** [comment] 2024-07-19 16:04
This is now a duplicate of the ISO default settings issue here: https://github.com/pop-os/iso/issues/332

**Closed by WatchMkr** 2024-07-19 16:04 UTC
