### ISSUE TITLE
Can't disable laptop display

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-settings#137] opened 2024-02-02 03:36 UTC
Note that this bug occurs with wdisplays too, so nothing to do with cosmic settings specifically. Also a bug with Pop on Wayland, so I'm pretty sure this is just a general wayland bug.

**Comment by XV-02** [comment] 2024-02-27 19:44
When you say that the bug is also present on Pop on Wayland, are you attempting to disable the display with `cosmic-settings` or with `gnome-control-center`? 

(`gnome-controll-center` will show up as just "Settings" in the dock, the application view, and when searching with the launcher in Pop on Wayland)

**Comment by chdalski** [comment] 2024-05-06 11:59
I can confirm this issue with EndeavourOS and the git version of cosmic-epoch. Trying to disable the laptop display doesn't work and it seems like the display is automatically reenabled because a short "flicker", for the lack of a better term, occurs.

**Comment by WatchMkr** [comment] 2024-05-09 19:57
This appears to be fixed.

**Comment by mmstick** [comment] 2024-05-09 20:02
Was fixed by the cosmic-randr updates recently

**Closed by mmstick** 2024-05-09 20:02 UTC
